### ISSUE TITLE
Version 1.0.0-RC6 - corrupt bam file output

### ISSUE THREAD

**Issue by GuyAllard** [PacificBiosciences/barcoding#3] opened 2018-01-25 14:58 UTC
Attempting to read query names from a bam file created by LIMA 1.0.0-RC6 using pysam.
Pysam raises the following error:
```UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 78: ordinal not in range(128)```

Coverting the bam file to a sam file using samtools 1.3.1 results in a nonsense sam file where the last digit of the query name is separated from the rest of the name by a tab.
e.g.
in the original basecalls bam file
```m171124_153019_42162_c101245642550000001823292201251830_s1_p0/69/45306_457```

but the sam-file created from the lima output:
```m171124_153019_42162_c101245642550000001823292201251830_s1_p0/69/45306_45    7```

The issue does not occur if I use LIMA 1.0.0-RC5

**Comment by pezmaster31** [comment] 2018-01-29 15:29
@GuyAllard I'm responsible for our tools' BAM I/Onsnd will be looking into this issue. The query name handling in BAM changed pretty recently & you may have hit some corner case. I'll keep you posted here on any developments.

**Comment by pezmaster31** [comment] 2018-01-29 15:34
Which version of pysam are you using?

**Comment by GuyAllard** [comment] 2018-01-30 09:47
pysam=0.13

**Comment by GuyAllard** [comment] 2018-01-30 09:48
sorry, accidentally hit the close issue button

**Comment by armintoepfer** [comment] 2018-02-02 15:09
Thank you for reporting this issue. We are investigating the issue in our core BAM library, as it is linked to a htslib change. We'll let you know as soon as possible!

**Comment by pezmaster31** [comment] 2018-02-02 23:57
I can't seem to reproduce this behavior, but I would definitely like to understand what's happening in your dataset to cause this.

Would you be willing to send your file to me via our PacBio secure upload site? If so, can you provide your email so I can send you a 'request code'? Feel free to contact me directly if you'd rather not post it here.  dbarnett -at- pacb -dot- com

**Comment by armintoepfer** [comment] 2018-02-06 11:13
I've updated the binary to link an older version of htslib. Please give it a try and report back.

**Comment by armintoepfer** [comment] 2018-02-09 14:45
Closing as it seems to be fixed now, if not, let me know!

**Closed by armintoepfer** 2018-02-09 14:45 UTC

**Comment by GuyAllard** [comment] 2018-02-12 08:59
I've just tested this, it appears to have fixed the issue.
Thanks!
